theme: App
title: UO-Navigate
description: An interactive 3D map of the University of Ottawa campus that helps students easily locate nearby facilities, including libraries, printers, AEDs, coffee shops, classrooms, and more. Navigate campus with ease and find the resources you need, right when you need them.
